module.exports.authService = require("./auth.service")
module.exports.userService = require("./user.service")
module.exports.roleService = require("./role.service")
module.exports.businessService = require("./business.service")
module.exports.productService = require("./product.service")
module.exports.tokenService = require("./token.service")
module.exports.genericService = require("./generic.service")
module.exports.chatService = require("./chat.service")